name: Maven and container build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
      
    - name: Login to GitHub CR
      uses: docker/login-action@v1
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: build container
      run: docker build . --tag "${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}"
      
    - name: Scan Image
      uses: anchore/scan-action@v6
      id: imagescan
      with:
        image: "${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}"
        acs-report-enable: "true"
        fail-build: false

    - name: Upload Image Scan SARIF report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.imagescan.outputs.sarif }}

    - name: Publish image
      run: docker push "${{vars.REGISTRY}/${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}"


      
      
