name: Maven and container build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    permissions:
      actions: read
      security-events: write

    steps:
    - uses: actions/checkout@v2
    - uses: snyk/actions/setup@master
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - name: SAST with Snyk
      run: snyk code test --sarif --sarif-file-output=snyk.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true
      
    - name: SCA, SAST with Snyk
      run: snyk test --sarif --sarif-file-output=snyk-sca.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      continue-on-error: true
      
    - name: Login to GitHub CR
      uses: docker/login-action@v1
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GCR_TOKEN }}

    - name: build container
      run: docker build . --tag "${{ vars.REGISTRY }}/${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}"
      
    - name: Scan Image with Grype
      uses: anchore/scan-action@v6
      id: imagescan
      with:
        image: "${{ vars.REGISTRY }}/${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}"
        fail-build: false
        by-cve: true

    - name: Upload Image Scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ steps.imagescan.outputs.sarif }}

    - name: Upload SAST Scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk.sarif
        
    - name: Upload SCA Scan SARIF report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: snyk-sca.sarif

    - name: Archive snyk scan results
      uses: actions/upload-artifact@v4
      with:
        name: snyk-sarif
        path: snyk*.sarif

    - name: Archive container scan results
      uses: actions/upload-artifact@v4
      with:
        name: grype-scan
        path: ${{ steps.imagescan.outputs.sarif }}

    - name: Publish image
      run: docker push "${{ vars.REGISTRY }}/${{ vars.OWNER }}/${{ vars.IMAGE_NAME}}:${{ vars.IMAGE_VERSION }}"


      
      
